---
title: "Development of the Nutrient Conversion Table for Tanzania National Panel Survey 2014-2014, Wave 4"
format: 
  html:
    embed-resources: true
editor: source
---

**Change log**

|Version | Changes made| Date|
|--|---|--|
|v.3.0.0 | Removed: all duplicated items. | 2023-11-28 |
|v.2.1.0 | Removed: some duplicated items. |  |
|v.2.0.0 | Changed: FCT preference order to KE18> WA19> US19 > TZ08 | |
|v.1.1.0 | Added: food dictionary names (`FoodName_3`) for all the food items, and re-organised the dataset. Changed: rice (husked) to white rice, tea dry to tea leaves. Excluded: duplicated values in item NPS15:1102, item (HBS18:117110) from item NPS15:603. | |
|v.1.0.7 | Excluded: herbal tea (too many missing values),  jambolan from fruits (missing vitamin A (RAE)), excluded grasshoppers (missing thiamine) | |
|v.1.0.6 | Excluded: sunflower and sesame seed from selection used for "cooking oil" (NPD15:1001). Fixed typo that duplicated paddy rice.| |


## Introduction

**Objective:** To provide the nutrient content of the food reported as consumed in the Tanzania National Panel Survey 2014-2015, Wave 4 (NPS15). 

**Output**: A dataset with the food listed reported as consumed in the NPS15 and their corresponding nutrient values. 

The food matching  is performed using the following scripts:

-  `01_food-list.R`
-  `02_weights.R`
-  `03_tz20_nct.R` 

The `03_tz20_nct.R` is also used to compile the Nutrient Conversion Table (NCT). 

Supporting & cleaning scripts are: 

-  `00_hbs18.R`
-  `00_tz08.R`


## Methods

### Data sources

#### Food consumption data

The Tanzania National Panel Survey has multiple waves, the National Panel Survey, Extended Panel with Sex Disaggregated Data (NPS-DSS 2019-2020) is the most recent, however the food consumption module was only collected in as subsample of the survey. Hence, the National Panel Survey 2014-2015, wave 4 was used. Both waves share the food list, hence this scripts could be used for the NPS-DSS 2019-2020.

There are two modules that provide information on food consumed. 

One module that provided information for food consumed outside household (Module F), which was excluded from the analysis, and the module that provided information on apparent consumption of food over the past one week at the household level (Module J1). The Nutrient Conversion Table (NCT) was prepared for the foods reported in this module and from now on is referred as the food list. 

The food list consisted in 60 key food items/ groups grouped into 12 broad categories: "Cereals and Cereal Products”, “Starches, Sugars and Sweets”, “Pulses, Dry”, “Nuts and Seeds”, “Vegetables”, “Fruits”, “Meat, Meat Products, Fish”, “Milk and Milk Products”, "Oils and Fats”, “Spices and "Other Foods”, and “Beverages". The food list is almost identical to previous rounds with only one item being subdivided into two. 

It also has a FFQ module (Module J3) and information on who shared the meal from outside household over the same period (Module J4). 

Other important modules may be Local units (Module CG) which provided information of the local measurement units used in the surveyed communities. The unique ids are combination of food id, food name and food item number, as multiple responses per food item were allowed.

Also, assistance and groups which provide information about whether the household received financial or in-kind assistance (i.e., food/maize distribution) (module O: Assistance and Groups, hh_sec_o1). 

The information above was extracted from the Basic Information document for the NPS (2014-2015) (@nsonpsbasicinfo2016)

#### Food Dictionary

### Tanzania HCES: 2018 Household Budget Survey {#sec-data.hbs18}

**Change log**

|Version | Changes made| Date|
|---|---|---|
|v.3.0.0| Removed the duplicated food dictionary (ID_3) in the NCT | 2023-11-27|

There are some food items that were excluded because they were problematic, for instance, herbal tea (23914.05) from US19(35238), as it has too many missing values. Similarly, in other to avoid duplication, some items were either excluded. For example, there were four entries for "chicken" ("21121.03") which is leading to duplicated items. The same found for other items such as rice, soft drinks (24490.02). Similarly, breads which were reported as slices and loaf ("111205", "111204", "111202") because were replicating the same food item in the composition.


```{r eval=FALSE}

subset(hbs_nct, grepl("chicken", food_desc, ignore.case = T))

```

Therefore, we decided to exclude all the duplicated but the one with the highest number of HHs reporting. We did not sum them, because it could be that one household reported two or more of the individual items in the list for which we used the same food items (composition). This led to the version (3.0.0). 
 
**Secondary output**: A dataset (`hbs18-tznct-weights_v.xxx.rds` (`hbs_nct`)) with the food listed as consumed in 2018 Household Budget Survey (HBS18), the number of household reporting consuming that food and their corresponding matches to the food dictionary. The variables in the dataset are presented in the @tbl-hbs18. 

|Variable name| Variable description|
|---|---|
| `food_id` | Food unique identifier of the food list of the 2018 Household Budget Survey.|
| `food_desc` | Food description of the food list of the 2018 Household Budget Survey.|
| `n` | Number of HHs reported consuming that food item in the 2018 Household Budget Survey. |
| `dict_testsample_code` | Unique identifer of the MAPS food dictionary (equivalent to `ID_3`). |
| `FoodName_3` | Unique food description of the MAPS food dictionary. |
| `Confidence` | Confidence of the matches between the food consumed in 2018 Household Budget Survey and the food dictionary. |

: 2018 Household Budget Survey NCT  {#tbl-hbs18}




#### Food composition tables & nutrient values

Identify the FCTs to be used. FCTs are normally selected based on a number of criteria, including geographic representativeness, data completeness and data quality. 

For these analyses FCTs were already selected and are reported in the protocol. Hence, the preference order was: TZ FCT, 2008 (TZ08) > Western Africa FCT, 2019 (WA19) > Kenya FCT, 2018 (KE18) > USDA FCT, 2019 (US19). 

Specific FCTs like uFish and/or uPulses may be used as well. 

The TZ08 needed to be cleaned as it haven't been used within the MAPS framework before. For more information on the steps and assumptions see the [GitHub repository]().

All the nutrients that are to be reported according to the protocol: Vitamin A, thiamine, riboflavin, niacin, folate, vitamin B6, vitamin B12, iron, and zinc, were reported in TZ08. However, there are other important information, such as edible portion, water (moisture) content, which were not provided. Hence, those values would be imputed from other FCTs (i.e., WA19). The nutrient comparison for values imputation will be done using energy. 

##### Tanzania Food composition table 

12. Maize, flour, dry: We used "maize, flour, white, refined, non-fermented, raw" (23120.03.02) because fibre and vitamin A values were zero, indicating refined (if bran was present there were some fibre), and white maize (as yellow maize owns its colour to the carotenoids (Vitamin A)). 

163. Cowpea, uncooked: Assumed to be the dry version by Energy (kcal) comparison. (1706.01)

204. Beef, boneless: We assumed beef, moderate fat (21111.02.02) because of the fat content () was similar to the one reported as "Beef, medium fat, cooked". 

490. Ginger: Assumed "fresh (root)" when comparing the Energy with the one reported in WA19. 

1108. Palm oil: It's red palm oil (VITA_RAEmcg = 5000mcg). We need a dict code for red palm oil!

###### Quality Issues

2. Bread roll: The composition values are the same as the "3. Bread, white". Hence, we are excluding that food item from the dict matches.

Sweet potato: Vitamin A (RAE) values were not consistent with the food item description (i.e, too low for orange flesh, and too high for "white"), similarly, it looked too high for sweet potato leaves, when compared with values in WA19. If the values were analysed samples and/or we could access the original values, we could consider including them as it may reflect country specific differences, however since it is not possible to check the original values and its quality, we decided to excluded from the matches. 


{{< include _01.food-matching.qmd >}} 


#### Step 3: Getting nutrient values from FCTs
